### ISSUE TITLE
gzipped files don't open anymore

### ISSUE THREAD

**Issue by joernhees** [joernhees/sublime-compressor#10]
i'm running into issues with gzip files, which just show up as hexdump...

i think the reason is the lazy loading in https://github.com/joernhees/sublime-compressor/blob/ed696e1d73a3ce54c1231ff952565c7544a30f4e/Compressor.py#L57

`sys.modules` only contains already loaded modules afaik, so gzip not being loaded for me lazily doesn't load it ;)

**Comment by dvhh** [comment]
My bad, forgot to check against gzip files, focused on bzip2 and lzma files
Just approved the change and will merge it

**Comment by dvhh** [comment]
Checked and released
