### ISSUE TITLE
attempts to decompress a file without a window

### ISSUE THREAD

**Issue by tgstaples** [joernhees/sublime-compressor#12]
Getting this stacktrace in the ST3 console.  Not exactly sure how to reproduce it but maybe checking for "is not None" would work-around the problem?

> Traceback (most recent call last):
>   File "/eda/sublime/sublime_text_3_build_3211/sublime_plugin.py", line 478, in run_callback
>     expr()
>   File "/eda/sublime/sublime_text_3_build_3211/sublime_plugin.py", line 517, in <lambda>
>     run_callback('on_load', callback, lambda: callback.on_load(v))
>   File "/home/tgstaples/.config/sublime-text-3/Installed Packages/Compressor.sublime-package/Compressor.py", line 278, in on_load
>     load_decompress(view)
>   File "/home/tgstaples/.config/sublime-text-3/Installed Packages/Compressor.sublime-package/Compressor.py", line 214, in load_decompress
>     for item in window.views():
> AttributeError: 'NoneType' object has no attribute 'views'

**Comment by dvhh** [comment]
getting a look
