### ISSUE TITLE
attempts to decompress file that does not exist

### ISSUE THREAD

**Issue by tgstaples** [joernhees/sublime-compressor#13]
Compressor seems to attempt to operate on a file that does not exist.  This can be reproduced when view a package file via the command palette.  Maybe an "os.path.isfile()" call would fix the problem?

> Traceback (most recent call last):
>   File "/eda/sublime/sublime_text_3_build_3211/sublime_plugin.py", line 478, in run_callback
>     expr()
>   File "/eda/sublime/sublime_text_3_build_3211/sublime_plugin.py", line 517, in <lambda>
>     run_callback('on_load', callback, lambda: callback.on_load(v))
>   File "/home/tgstaples/.config/sublime-text-3/Installed Packages/Compressor.sublime-package/Compressor.py", line 278, in on_load
>     load_decompress(view)
>   File "/home/tgstaples/.config/sublime-text-3/Installed Packages/Compressor.sublime-package/Compressor.py", line 224, in load_decompress
>     suffix = decompress(filepath, file_temp)
>   File "/home/tgstaples/.config/sublime-text-3/Installed Packages/Compressor.sublime-package/Compressor.py", line 176, in decompress
>     suffix, decompressor = get_decompressor_by_header(source)
>   File "/home/tgstaples/.config/sublime-text-3/Installed Packages/Compressor.sublime-package/Compressor.py", line 105, in get_decompressor_by_header
>     file_size = stat(filename).st_size if filename else 0
> FileNotFoundError: [Errno 2] No such file or directory: '/home/tgstaples/.config/sublime-text-3/Packages/Default/colors.py'

**Comment by dvhh** [comment]
getting a look
