### ISSUE TITLE
Request package control ownership

### ISSUE THREAD

**Issue by dvhh** [joernhees/sublime-compressor#4]
request for ownership change over [package control channel entry](https://github.com/wbond/package_control_channel/blob/master/repository/c.json#L3166), would allow for better maintenance (like tagging the new release for bringing latest improvements to end users)

**Comment by joernhees** [comment]
yupp, didn't have a lot of time for this in the past :-/

We can either transform this into a small github org or you can simply continue here (added you to this repo).

**Comment by dvhh** [comment]
Thanks, let's continue from here as it is currently the simpler path
