### ISSUE TITLE
compression modules not loaded reliably

### ISSUE THREAD

**Issue by tgstaples** [joernhees/sublime-compressor#6]
I have noticed that compression modules are not loaded reliably.  On our RH7 Linux machines, I only get bz2 on ST3 startup.  Here is a snippet from the console...

```
reloading plugin Compressor.Compressor
bz2
plugins loaded
```

If I disable/enable Compressor while ST3 is running I get bz2 and gzip...
```
ignored packages updated to: ["Anaconda", "Compressor", "Vintage"]
unloading plugin Compressor.Compressor
reloading settings Packages/User/Preferences.sublime-settings
ignored packages updated to: ["Anaconda", "Vintage"]
reloading plugin Compressor.Compressor
bz2
gzip
reloading settings Packages/User/Preferences.sublime-settings
reloading settings Packages/User/Preferences.sublime-settings
```

I think this issue can be fixed by using plugin_loaded() ST3 api like below and remove the call load_modules() in the OpenCompressedFile3() constructor.

```
def plugin_loaded():
    load_modules(COMPRESSION_MODULES)
```

**Comment by dvhh** [comment]
Looking at it, thanks for the suggestion

**Comment by dvhh** [comment]
@tgstaples  would you kindly test my fork which implement your request ?

**Comment by tgstaples** [comment]
> @tgstaples would you kindly test my fork which implement your request ?

Appears to be working.  Thanks!

```
reloading plugin Compressor2.Compressor
plugins loaded
gzip
bz2
```

**Comment by dvhh** [comment]
thanks for confirming
